---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: office
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .NEXTCLOUD_DBUSER }}"
        password: "{{ .NEXTCLOUD_DBPASS }}"
  dataFrom:
    - extract:
        key: nextcloud
