---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-db
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: "{{ .AUTHELIA_STORAGE_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: postgresql
