---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: redis
