---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHELIA_SESSION_REDIS_PASSWORD: "{{ .AUTHELIA_SESSION_REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: authelia
