apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:XXRnqhTe3dLEK6I9PpoE1oZaRqSBXl8qUSDTHVkdwutY1emd,iv:4xlJm7+1s2xnfuddAZOKpwKH3XqD4dGgcmhRUtMoZ3U=,tag:1Rhp2B7TnHVTQuibeJtAcQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Olqt3zHsy2Pe9WYJ5jxKzCpE/EVPXSJvA0mdXJUIgDTjNUF4v9+JZ15t67jEK8DluJNq1WZBvvzMuisXlSq9w5gy6RS+3eaFfYJ9axrTqs6HEywITRC7FiKa9xoe8SDDqRiL/b88CC9ubv3J17rclf/m3Lw/3pm3TPOxC0cik7obPVUscPfqZKYvX3TtS36wxoVw3ba2D09Ggu3EWmz9PUuaXFaiiosDRmHGMui75Q==,iv:gbYakJnEfROGqEs0v1wdrDc5GYD1n6w5V5wvBAPIAKw=,tag:mof+te2VaUcikv3gnMwRfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n9l6uxhz0dt3v9qxmcp7492ftrnxlmtwq4yrzd4kr0j9zzkepa9ssqfq23
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S3VRUmdLOGY0d3ZybGNV
            VW5tOVNKMUovdlNvS2N4L0hwTTZ6WCt1bVdJCnE3RGdOSkpWOWR4YVdMNDAxZ0RW
            S1llVENmVjh0QXJtYkFiSWJoajAwZW8KLS0tIFVnU1AzeHAvbWhka0NNcHhqZjZm
            OEdaR1dYK2plTnRXeVhYcE5Nb25HSWMKMS/ohWP8gg6VgChzdRnFWhlm6U071fyn
            r/Pi2Sri11PQYrWAO33yWzaxbSXZ6s58tSgvo9mEePDIe/hJowaUug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T16:37:03Z"
    mac: ENC[AES256_GCM,data:XpFnj3Ux2Nn9ZZjBipfV8dwHv//s3ZPkWcPKS/VWo8Wo2BWS7i0VTBrnVyFxj/hDbMsFrMFyjJ4ky07Ibl2IsMiFaAcmKK9iv97vCWaOqimUhB3uIWMPnmtPFCbStdm/vwad61LAk9dSqLoIseLFOgBdwXfk/+jdoXJ2S+r/qXo=,iv:7OIuD8M8dePG+A4Rnwh2El1lZPaIVJNhZ/Bv2i1p71g=,tag:TDvYZlRw8c5ganHwfsw14A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
