---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: authelia
      version: 0.8.58
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: lldap
      namespace: security
    - name: authelia-redis
      namespace: security
    - name: authelia-postgresql
      namespace: security
  values:
    domain: ${SECRET_DOMAIN}
    ingress:
      enabled: true
      subdomain: auth
      tls:
        enabled: true
    pod:
      kind: Deployment
      replicas: 1
      strategy:
        type: Recreate
    configMap:
      enabled: true
      theme: dark
      totp:
        disable: false
        issuer: "${SECRET_DOMAIN} Authelia"
        algorithm: sha1
        digits: 6
        period: 30
        skew: 1
        secret_size: 32
      webauthn:
        disable: false
        timeout: 60s
        display_name: "${SECRET_DOMAIN} Authelia"
        attestation_conveyance_preference: indirect
        user_verification: preferred
      duo_api:
        enabled: false
      authentication_backend:
        password_reset:
          disable: true
        refresh_interval: 5m
        ldap:
          enabled: true
          implementation: custom
          url: ldap://lldap.security.svc.cluster.local
          timeout: 5s
          start_tls: false
          base_dn: dc=home,dc=arpa
          username_attribute: "uid"
          additional_users_dn: ou=people
          users_filter: "(&({username_attribute}={input})(objectClass=person))"
          additional_groups_dn: ou=groups
          groups_filter: "(member={dn})"
          group_name_attribute: "cn"
          mail_attribute: "mail"
          display_name_attribute: "displayName"
          permit_referrals: false
          permit_unauthenticated_bind: false
          permit_feature_detection_failure: false
          user: uid=admin,ou=people,dc=home.dc=arpa
      access_control:
        default_policy: two_factor
        networks:
          networks:
          - name: internal
            networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
        rules: []
      session:
        name: ${SECRET_DOMAIN}_authelia_session
        same_site: lax
        expiration: 1h
        inactivity: 5m
        remember_me_duration: 1M
        redis:
          enabled: true
          enabledSecret: true
          host: authelia-redis-master
          port: 6379
          database_index: 14
          maximum_active_connections: 8
          minimum_idle_connections: 0
          tls:
            enabled: false
      regulation:
        max_retries: 3
        find_time: 2m
        ban_time: 5m
      storage:
        postgres:
          enabled: true
          host: authelia-postgres
          port: 5432
          database: ${AUTHELIA_DB_NAME}
          schema: public
          username: ${AUTHELIA_DB_NAME}
          timeout: 5s
      notifier:
        disable_startup_check: true
        smtp:
          enabled: true
          enabledSecret: true
          host: mail.${SECRET_DOMAIN}
          port: 465
          timeout: 5s
          username: mail@${SECRET_DOMAIN}
          sender: Authelia <authelia@${SECRET_DOMAIN}>
          subject: "[Authelia] {title}"
          disable_html_emails: false
          disable_require_tls: false
    secret:
      existingSecret: "authelia-secret"
