---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  # App
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # Database
  - ./helmrelease-redis.yaml
  - ./helmrelease-db.yaml
  - ./pvc-db.yaml
  - ./pvc-redis.yaml
