---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-db
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .LLDAP_POSTGRES_USER }}"
        password: "{{ .LLDAP_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: lldap
