---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: longhorn-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: "{{ .SERVICE_ENDPOINT }}"
  dataFrom:
    - extract:
        key: service-k3s-longhorn
