---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      backupTarget: s3://k3ssrv-longhorn@eu-central-2/
      backupTargetCredentialSecret: longhorn-secret
      defaultReplicaCount: 1
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: true
      replicaAutoBalance: true
      storageMinimalAvailablePercentage: 1
      storageOverProvisioningPercentage: 100
      defaultLonghornStaticStorageClass: longhorn-backup
      restoreVolumeRecurringJobs: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      guaranteedInstanceManagerCPU: 20
      orphanAutoDeletion: true
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
    metrics:
      serviceMonitor:
        enabled: true
