---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL_NAME: "{{ .AUTHENTIK_POSTGRESQL_NAME}}"
        AUTHENTIK_POSTGRESQL_HOST: "cnpg-authentik-rw"
        AUTHENTIK_POSTGRESQL_USER: "{{ .AUTHENTIK_POSTGRESQL_USER }}"
        AUTHENTIK_POSTGRESQL_PASSWORD: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
        AUTHENTIK_REDIS_HOST: "redis-lb.database"
        AUTHENTIK_REDIS_PORT: "6379"
        AUTHENTIK_REDIS_PASSWORD: {{ .REDIS_PASSWORD }}
        AUTHENTIK_REDIS_DB: "1"
        AUTHENTIK_EMAIL_USER: "{{ .AUTHENTIK_EMAIL_USER }}"
        AUTHENTIK_EMAIL_PASSWORD: "{{ .AUTHENTIK_EMAIL_PASSWORD }}"
  dataFrom:
    - extract:
        key: authentik
        key: redis
