---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: *secret
    valuesFrom:
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_SECRET_KEY
        targetPath: authentik.secret.key
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_POSTGRESQL_HOST
        targetPath: authentik.postgres.host
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_POSTGRESQL_NAME
        targetPath: authentik.postgres.name
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_POSTGRESQL_USER
        targetPath: authentik.postgres.user
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_POSTGRESQL_PASSWORD
        targetPath: authentik.postgres.password
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_REDIS_HOST
        targetPath: authentik.redis.host
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_REDIS_PASSWORD
        targetPath: authentik.redis.password
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_EMAIL_USER
        targetPath: authentik.email.username
      - kind: Secret
        name: *secret
        valuesKey: AUTHENTIK_EMAIL_PASSWORD
        targetPath: authentik.email.password
    authentik:
      log_level: debug
      avatars: "gravatar,initials"
      email:
        host: mail.${SECRET_DOMAIN}
        port: 465
        from: "Access <access@${SECRET_DOMAIN}>"
      error_reporting:
        enable: false
        send_pii: false
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
    server:
      autoscaling:
        enabled: true
        minReplicas: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
        hosts:
          - &host id.${SECRET_DOMAIN}
        paths:
          - /
        tls: [hosts: [*host]]
    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
    prometheus:
      rules:
        enabled: true
