kind: Service
apiVersion: v1
metadata:
  name: authentik-ldap-outpost
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ldap.${SECRET_DOMAIN}"
    io.cilium/lb-ipam-ips: ${SVC_LDAP_ADDR_V4}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 3389
    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 6636
    # - name: http-metrics
    #   protocol: TCP
    #   port: 9300
    #   targetPort: 9300
  selector:
    app.kubernetes.io/name: ak-outpost-ldap
    goauthentik.io/outpost-name: ak-outpost-ldap
    goauthentik.io/outpost-type: ldap
