kind: Service
apiVersion: v1
metadata:
  name: authentik-ldap-outpost
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ldap.${SECRET_DOMAIN}"
    io.cilium/lb-ipam-ips: ${SVC_LDAP_ADDR_V4}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 3389
    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 6636
    # - name: http-metrics
    #   protocol: TCP
    #   port: 9300
    #   targetPort: 9300
  selector:
    app.kubernetes.io/name: authentik-outpost-ldap
    app.kubernetes.io/managed-by: goauthentik.io
    goauthentik.io/outpost-name: ldap
    goauthentik.io/outpost-type: ldap
    goauthentik.io/outpost-uuid: 7b31ff3b6b764538aa529348892c403a
