apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:bRCAAZa44ZY8elyMlGxcu8FB74zERsSmKQ7UTzv2+TAuPXltF6j92Q==,iv:qWwDolGY3gMbz/0BwoMwlajx8mtv+O7sqYMgWzeehjQ=,tag:efSDgJXWg0je3utzzGF2BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykegsmjhpgzqh7dw6d9tqgtyavqrr3w0mrrmgx33cyyc43uxd5gskezvvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WEhvVHplK2o0blR4U3k1
            T3k0NCtDYjRlZG4yeVFSNm9TYnpib1ZsR0ZRCkUrMDBUNHczNmN1UnNvelJJZVl5
            SUs4T2hvQWwrVVlONGE3ck5zMUkvbG8KLS0tIHpseUE1MldpMUIycUErTE9RYlhX
            UCtpN0pBTTczeHprOW9zN1FGeDBXNXMKmZ+AraCrPjaQrPojL23x9B6wTZtLG+B3
            pq6I5pN2qwf5/7+qlzL2qRcUqBJsmHLQO+Yn896xoOtvOG8+cXBUbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:48:29Z"
    mac: ENC[AES256_GCM,data:8NTyapC2g+Uzi4+yIYXXy8MqpTFJ56Fmbcj+jUk0uXLyGoSzRccXePJHy4eQGHl1Z4l5hiFf0UAlpdu+yrRjbxzsRU5fAtMKJMwJwQP/PA1I8E/Xugu7NR0L53xUi2ZNHGVLiSCECnNKcj9KeD7aXMS6SGdvEZCV4fD+K2deKHg=,iv:2AUdQKw/6aYSHLM8FGIYHgeCWOk24Kb2QZzf9pG2e4M=,tag:PAOFv9g0chykKtx/OvQPIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
