---
authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: ldap://lldap:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: uid=admin,ou=people,dc=home,dc=arpa
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

password_policy:
  standard:
    enabled: false
    min_length: 12
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: true
    min_score: 3

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: ${SECRET_DOMAIN}_authelia_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
  redis:
    host: authelia-redis-master
    database_index: 14

notifier:
  disable_startup_check: true
  smtp:
    address: submission://mail.${SECRET_DOMAIN}:465
    username: mail@${SECRET_DOMAIN}
    sender: Authelia <authelia@${SECRET_DOMAIN}>
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: false
  display_name: ${SECRET_DOMAIN} Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

duo_api:
  disable: true

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules: []
