---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_ADMIN_USERNAME: "{{ .NEXTCLOUD_ADMIN_USERNAME }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        NEXTCLOUD_TOKEN: "{{ .NEXTCLOUD_TOKEN }}"
        NEXTCLOUD_SMTP_USERNAME: "{{ .NEXTCLOUD_SMTP_USERNAME }}"
        NEXTCLOUD_SMTP_PASSWORD: "{{ .NEXTCLOUD_SMTP_PASSWORD }}"
        NEXTCLOUD_SMTP_HOST: "mail.${SECRET_DOMAIN}"
        NEXTCLOUD_POSTGRESQL_HOST: "cnpg-nextcloud-rw"
        NEXTCLOUD_POSTGRESQL_DB_NAME: "{{ .NEXTCLOUD_POSTGRESQL_DB_NAME }}"
        NEXTCLOUD_POSTGRESQL_USERNAME: "{{ .NEXTCLOUD_POSTGRESQL_USERNAME }}"
        NEXTCLOUD_POSTGRESQL_PASSWORD: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud
