---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 4.6.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    image:
      flavor: fpm-alpine
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret nextcloud-secret
    replicaCount: 1
    nextcloud:
      extraEnv:
        - name: REDIS_HOST
          value: redis-lb.database.svc.cluster.local.
        - name: REDIS_HOST_PORT
          value: "6379"
      strategy:
         type: RollingUpdate
      host: &host cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: NEXTCLOUD_ADMIN_USERNAME
        passwordKey: NEXTCLOUD_ADMIN_PASSWORD
        tokenKey: NEXTCLOUD_TOKEN
        smtpHostKey: NEXTCLOUD_SMTP_HOST
        smtpUsernameKey: NEXTCLOUD_SMTP_USERNAME
        smtpPasswordKey: NEXTCLOUD_SMTP_PASSWORD
      mail:
        enabled: true
        fromAddress: admin
        domain: "${SECRET_DOMAIN}"
        smtp:
          secure: ssl
          port: 465
          authtype: LOGIN
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array(
               0 => '${CLUSTER_CIDR}',
               1 => '192.168.0.0/16'
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'trusted_domains' =>
            array(
               0 => 'cloud.${SECRET_DOMAIN}',
               1 => 'id.${SECRET_DOMAIN}',
            ),
          );
        user.config.php: |-
          <?php
          $CONFIG = array (
            'default_language' => 'de',
            'default_locale' => 'de_DE',
            'default_phone_region' => 'DE',
            'default_timezone' => 'Europe/Berlin',
            'maintenance_window_start' => 1,
          );
        bulkupload.config.php: |-
          <?php
          $CONFIG = array (
            'bulkupload.enabled' => false,
          );
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
    persistence:
      enabled: true
      existingClaim: nextcloud-pvc
    startupProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 360
      successThreshold: 1
    livenessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
      tls: [hosts: [*host]]
    nginx:
      enabled: true
      config:
        default: true
      resources:
        requests:
          cpu: 50m
          memory: 20Mi
        limits:
          memory: 100Mi
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: false
      type: postgresql
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: *secret
        hostKey: NEXTCLOUD_POSTGRESQL_HOST
        databaseKey: NEXTCLOUD_POSTGRESQL_DB_NAME
        usernameKey: NEXTCLOUD_POSTGRESQL_USERNAME
        passwordKey: NEXTCLOUD_POSTGRESQL_PASSWORD
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            memory: 20Mi
    metrics:
      enabled: false
      https: true
      serviceMonitor:
        enabled: false
    cronjob:
      enabled: true
