---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 250Gi
