---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 150Gi
