apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    LLDAP_DB_NAME: ENC[AES256_GCM,data:ByB2LE0=,iv:qQVaFf5cA3EY4bAl0r5yo/WKc7Gt60E0DR+KYTKRTKU=,tag:COmVg/Gei411EeZPnSJkJQ==,type:str]
    LLDAP_DB_USER: ENC[AES256_GCM,data:YYgSnXP1DUY=,iv:c6wlzPuHinE7eB5I4qNcQ2X98+QsSdKsrt2bMTHbQSM=,tag:ui2ZcdxSgA1ZIHu0G7FnIw==,type:str]
    AUTHELIA_DB_NAME: ENC[AES256_GCM,data:HJkaLUbg3aU=,iv:5qcQ2cSj0Zrna0xUmPPVXsGVyavbXoNIYuL4cU6sMTM=,tag:vEhu3Ea4LNDupXkcOWiqYw==,type:str]
    AUTHELIA_DB_USER: ENC[AES256_GCM,data:HWXwmb16g4jYB0o=,iv:XIumqg++9Bu2RrWPp5pE6wVE3J+dT/p45n4qIlaxRc4=,tag:aRGz/pEBKpLPVe9kPbn8+Q==,type:str]
    PAPERLESS_DB_NAME: ENC[AES256_GCM,data:/t70wp4FI1/k,iv:XuxFAaniOkr7kntrPaLH5xC1FW9wnejGyZAW7GZZxpA=,tag:NtpYH5PQRzoROy0xSEd63w==,type:str]
    PAPERLESS_DB_USER: ENC[AES256_GCM,data:pC9iNtcHXeS0LlnC,iv:XuhtKIiI95B68Y5XQzZeETKebzQch4f6p9NI4p0725w=,tag:nox8OY4aeviZ+WHAFJupuA==,type:str]
    NEXTCLOUD_DB_NAME: ENC[AES256_GCM,data:1uhX5Xzx2Jte,iv:a8zqPZzbg1z59hkm4EXmNOhcjR09DQEUS/puCRDUSgY=,tag:dgV94mkVfLQX0b/TNLAzDA==,type:str]
    NEXTCLOUD_DB_USER: ENC[AES256_GCM,data:EWDs85RNhX/xxKcP,iv:7ZmAvaij4H6DUfltc5Mc5XxWvuMGw3+ImnvUM3pbMoA=,tag:Uhb0iqfvDe/+mDn538L6WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykegsmjhpgzqh7dw6d9tqgtyavqrr3w0mrrmgx33cyyc43uxd5gskezvvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISDg3SzJROXFiaWQxays2
            b3BneEw4YnE4YlpGMlhzUjRBeXEyR3NvMFZjCm83R3dCQ016encyV3JTOGhtZWFv
            YmlZczB5S2d1NG52emV2QVBhWW16bncKLS0tIG1WRUlXUS8zZHYyZVpyeDIwTW9V
            MmlIbWZ1eWNPd0lxcWlPc1FiNjgzd2sKJv/+sUV/wV352VWvv4fxQ3I8nGZCPHOU
            ZlS03BBK0Brll13fyszXnHiBcZRD0mkDW9bXYsbTBpOoHTr1j+E14Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T18:56:18Z"
    mac: ENC[AES256_GCM,data:ac/OqkU8SyCIkmn9635b+KtRywFjsr/Qabi7SAuCaDnGdC0ccA2ONYIKeES+IY9Y/2Og36zP4M7uNUS63Oc5myJur3eIkJ/+c+2iNWM8/2xzaeNsqC1ds9zpmD4jozJQb+h/QBag6+hYuhsCo+8R2+E3TkctSTztd/Y8iMNop8Q=,iv:2iOAKSBSWoRT4vQPU3tJ/PJ2r+ZTGtvsPfoPLz8T0IM=,tag:9kLNUqGswpOvhSkNhty8OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
