apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U44VKIJIi868UahaV08u,iv:c73dstzPrV71xu79sjlgQtfAcVCQmjDSKPP/ayzXRXg=,tag:cSPATrqAHJguUImG6ghkFg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IGKnT9mZ7XpodXrNqLJLWDJ7WewfKMCuSpMvhKskli3XTCY8,iv:aUdsUM2EZbXjMjitx3C/c48feXgIwnu1awKBr8sJph0=,tag:R4aU86grY2RrmVYZf3qrNw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:clQAvVhWbTG3Ow==,iv:izfaYY5nOQmbEVNnHEh+xExO7GECq5pbJ0qck4cBSCU=,tag:ZOql6OG/6g8xNx4aEeCIMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykegsmjhpgzqh7dw6d9tqgtyavqrr3w0mrrmgx33cyyc43uxd5gskezvvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSU41Z3k5eTZEWlFlYmRG
            eERYWnd3dnh6SnNHTW41UGg1RWhHZml6V1FnCk1yam5Fb3JONlY0SGFmZHBhZGc2
            ZVpiOTFrTDljS3Z6Vmwrdy9iSFBtbE0KLS0tIFk0c0R3bWtldTM0T3ZjQ2xGZlNK
            NnpxUnJZQmtPTlBKdkFuUDU0MDZXTW8Ki85MIC2vybBX+7BF9MfjIz2EU7rqkXAz
            hUFAOpZcibWKrDCBpckGWbAPNOTOPg4HfZ3NFELIIz8XmI6k5Dz3wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:48:29Z"
    mac: ENC[AES256_GCM,data:mUZT0EuDYO4id0g++++Xzo+P8NTOFQ9JhhXyYiW+smeQW5ip7T3Mr9sXDqVgrbnXfY5FOgUEQRNqLPRxbA0Lsob2/5B9THrQMosOzNF4/QzgbEkELpAu3p2f+o2hcp8uEz/aeQNSr+JlBjgcBXaVVsLX2GEZzs6eJHw+Sny1Ssk=,iv:RAjiP+eWLPx1kZoxaXOJN6sRhsX7ijDWMNJ12AOdi3I=,tag:Z5uMLEyyoKL6Ki3uxCvsFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
