apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    LLDAP_DB_NAME: ENC[AES256_GCM,data:gfD4YxE=,iv:0YNOeS7F+qrqvdmg6ulceO2InFPq64LgDY6U1N5R6t4=,tag:6Yz9eCYnMJddDgXuHse1iA==,type:str]
    LLDAP_DB_USER: ENC[AES256_GCM,data:2XeRqQdL59w=,iv:Gteelbwb0sc4ldsgeCkTKuDIRnLBXPkuujXxOndkZZk=,tag:UtN0zhq5lBXU28KtUMw0wg==,type:str]
    AUTHELIA_DB_NAME: ENC[AES256_GCM,data:FMb6pQWcMF4=,iv:3AYd/LVTuUDzNV8SG8Fe81FPzIQV0heVY3LkxTI6txo=,tag:d13jXNHsJ3iPd6kvg9yYdg==,type:str]
    AUTHELIA_DB_USER: ENC[AES256_GCM,data:IbghJ2Y6ORtlc/E=,iv:ELgTvdpHNbOs/mQQ+qpDedmE9BBZRO0ZXgZ/61bSDSw=,tag:uFveYehItSv4IKNmD+UNmA==,type:str]
    PAPERLESS_DB_NAME: ENC[AES256_GCM,data:pLYhIUWSoKCY,iv:6eMRGdI8s7fH9UXUPUpuwi6Dn3OL5BThY6zO9uz2dWA=,tag:z27+0CZXAxELDnsgCB2YRw==,type:str]
    PAPERLESS_DB_USER: ENC[AES256_GCM,data:3//zw0uaOiu/Jn7y,iv:JyfLaTXeaaTnOa1wiyiCnM1KT0WcAyt8vzDH402+Jak=,tag:jPlGASM9igasaIiSYXdpPw==,type:str]
    NEXTCLOUD_DB_NAME: ENC[AES256_GCM,data:jX1dkpp3S3Xm,iv:J/vBGzj+SafGWUmvtdyGjkmrS9ju+sJIyjW0gJJBkXA=,tag:BM65Pemfb6epuNCIfUj6Ew==,type:str]
    NEXTCLOUD_DB_USER: ENC[AES256_GCM,data:sajJ/zlIB9eMOc0x,iv:mhayk/oOHPh61ON1tqpagEyiO2BQGAWnWaW+mgAN1ps=,tag:xpNNzGq8Fwkt0fx1pt9o/Q==,type:str]
    LLDAP_DB_NAME: ENC[AES256_GCM,data:oEFCdAM=,iv:Bt0/UKux3PcTPXzJIX5z+A6KgjRZkLZXQ6Jntuw5g+4=,tag:yxXof9d5RAzFbRIdxQ8Rig==,type:str]
    LLDAP_DB_USER: ENC[AES256_GCM,data:VNW1QNlWPB0=,iv:L1cHQJ7sXiqq863flgVNO3w1dW+Uw/GxtRSAv9WudvQ=,tag:L4C4M2c0Vy1Ro5h7kwuj4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykegsmjhpgzqh7dw6d9tqgtyavqrr3w0mrrmgx33cyyc43uxd5gskezvvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpblhwQzVrakk2Q2JId3FB
            c21mbFZMU0NYWW9lQ1krVG9SRzlPL3JHcFNvClhvTlBxUE5Uc2lLSDZhY2gzRFB2
            bHQ0dy84WFB2c2pjcVFEWUc2RHJxUFkKLS0tIEZpT2NoWVAyUjRGMUIyNGJ3b0Zs
            N1VFajIyWVlaazhHcDBDZXFuWEMwdDAK7eM2/qg1nD45yynlbGhep5XQJTWvdhCQ
            LK5L5zrFEUhku2/FtktZbhdRyRgJbzPdlNYt6yd+qtCimozPXbe9oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T19:41:38Z"
    mac: ENC[AES256_GCM,data:xScU2WAcQGNyd5GW0mjHalDVjJIt4l+1+dd6N2B5VLOGMk9N95mvi3YnjJOJ5baZuY+/kfHNq7zSR2AJ145rWydLvVGevwKGfthijRf/zESvey9aucQZT7pbDmCqkqK/jTEJiuxF228HkFGb0WLbnLRjf4/neSVXvbV6UQRv8uo=,iv:I1iplptyhix2bS2mcepxcwJUozvXRc/Mpkdyhgbh8TY=,tag:pUCAAGMvUQr9PAaf5/X8fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
