apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    LLDAP_DB_NAME: ENC[AES256_GCM,data:FPxSgnQ=,iv:nd2wQzb3H/LIvX7U3YpLyo1FZ+8rqkLIwPcbufcwPmQ=,tag:li/JcVA9GO/G8ZMhOXPyyw==,type:str]
    LLDAP_DB_USER: ENC[AES256_GCM,data:yQEYiqJrxgU=,iv:F2DEQ2ccs4WnxVsdVKJ677kJx9deuAzRJwT73O5VJW8=,tag:oETULTTWv1tH2YJ2b0tyrA==,type:str]
    AUTHELIA_DB_NAME: ENC[AES256_GCM,data:cidSOD/8M6k=,iv:aA2tqvhU9NVtrC2ShfAf7EJqnrqO+mAI48NQzHsW16g=,tag:Dl4dRIn6ygNWbiZbbSIEVQ==,type:str]
    AUTHELIA_DB_USER: ENC[AES256_GCM,data:1HuQhNFmhG113Yc=,iv:aJht9UduACH4aSLDTC4Wemfj3fdFaHF9xWS+eaRUKwE=,tag:PVGcPOW59af7CGdpSBHf1g==,type:str]
    PAPERLESS_DB_NAME: ENC[AES256_GCM,data:v2y3YIrUAzaU,iv:5SkHbWOk2sYqyeW1pywDFp4PlbJUZR/oVNIKvDIf5uY=,tag:fN5CIbaXdImR6d+PSiCyWg==,type:str]
    PAPERLESS_DB_USER: ENC[AES256_GCM,data:H4OvNqD3OJP+T59t,iv:tzLh67h7+H9Ajl4yYmsmrh9pAO4el2E3UDU+12Zcy7A=,tag:J7s873zx91yUT8uxkoZlNg==,type:str]
    NEXTCLOUD_DB_NAME: ENC[AES256_GCM,data:85yn82dg/6CR,iv:ICNtbzL3T92L6hmDbhyvMjQwTrqqgSz1hP91WY59T1A=,tag:2yQI1nTWQsPXoXfg7vQ4GQ==,type:str]
    NEXTCLOUD_DB_USER: ENC[AES256_GCM,data:0PTZDiBjGVxUBJbS,iv:OBwDdABAw/322oMiNLev2pNWTY1sJVDhlWhXPwUBpz4=,tag:7+KATUYJKwQn6qkI2gKLCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykegsmjhpgzqh7dw6d9tqgtyavqrr3w0mrrmgx33cyyc43uxd5gskezvvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d3dWU05KZmh2Nk5iYjVI
            dEM3MGpBeXRWZmc4VDFiWHlJS0RISkVLSXpFCmlHZUN1SXNhSmV2L2UvaXlVUzhQ
            OGt3cWIxYVVGM1MzOEpHTHdCeWxSckEKLS0tIE1qYzBhcDJsaUhDZGVqd1Zock9B
            eFF5MU5GeVVCZEMyc2xaTHM4YjJSNjQK34ntasT2wQIzfYwY5TlT73cz0cTvthSA
            Hh9gapl9Jx1oYMvtveCIxO7JYH8jkY/PG6dGLssMV0pBkXDwqDvbgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T20:59:22Z"
    mac: ENC[AES256_GCM,data:2f1R8yXGDuyP9ydpL27XtECDXgHV/L26t2cdjuHdv/0oavC02816mzFgxJV1gAw35FhtzOmnmbovwvv4pVgMW3lujjqZmExOTJb9kqxlH/tJvYSHIoruNuSsP3FmI1wIBmRZW7dAZNNwj9J+QDyfQ/ZkhpdA3YWTA6NO/+SfUlY=,iv:f/HZ/cFwxJQlBY4P8OM7zJWwMxTrYqklF6l65OjO8Gs=,tag:eJfEaN3OPJZimGscjmjymw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
