apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Gt1YSY7lp0UiCg==,iv:mpGn3Lr0Z1KO+R/590b5YJEHULilwn2JNicXSrPmDkE=,tag:oZrf/Y3DzJf/Lbu6ZxpI0A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Yd04gyPtUuATycbS52uL,iv:XLWykgeOd74dx05umUrokHqz3OUBMxs1xXpO5C1c/Iw=,tag:9SF7xk7PUv2p22L1v2Y4GA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:kexJMiq14Lk+SP/rVWxEr5ykhxysCsPE449oAYm/0tYabvmt,iv:UJkOoNdUeRCZJ0zVdvdiR5YPp0l4nGby/rzo3pW52bw=,tag:Ir5M153iEo+WHpFfZSjHVQ==,type:str]
    AWS_ENDPOINT_URL: ENC[AES256_GCM,data:AtAWk9S8AHgwRX9IsSrtugw8rKD0tgapC3mwxAOo8nT8k0XTbg==,iv:nO8xe1Ofe9ZiD2Ff24X3LVZw5APhW+YzqBF8AsSp/7w=,tag:KCpcxeDefLhyB2JVGvcrpQ==,type:str]
    AUTHENTIK_DB_NAME: ENC[AES256_GCM,data:q63RGVvYXo1QOH4=,iv:QLgTWeX8+RGpDPt5kcZrdFUDd62rE4uHbLJW9WzFeRY=,tag:cBjKe6Pwahw9TsPSp3R8ZA==,type:str]
    AUTHENTIK_DB_USER: ENC[AES256_GCM,data:z1lMwOUiaIqDRoeQ,iv:Na3Kcaxsht+qtelqvoFpJfpQ/p+4YmZKYIn1AUtHxHk=,tag:6WXdQau7TJRH01krFVx4+w==,type:str]
    NEXTCLOUD_DB_NAME: ENC[AES256_GCM,data:6RiM62pL8W95Prs=,iv:PRWbJFdhicSZeLW7BuCgvkXY18Axx6Cl6NHxz1CKL3w=,tag:qbDTvFiSuFgoX4V03yRiCA==,type:str]
    NEXTCLOUD_DB_USER: ENC[AES256_GCM,data:gfLsOE80+SoMqVsH,iv:tl3cxc61qQDatpzoA7CiW7FB1hDd2BNX8gDV7ia4d9I=,tag:HYl8cT/F/EIK+sAa7M6hCw==,type:str]
    PAPERLESS_DB_NAME: ENC[AES256_GCM,data:meU0+EduEs7x0Q8=,iv:xMApHsl1D5EEfdRaq/fq7jGjGXCtPn4YwmbZ2wLmAJE=,tag:7Q77/qQH3CDutIXYjbxDsg==,type:str]
    PAPERLESS_DB_USER: ENC[AES256_GCM,data:EaAqmYefY0qTKTgo,iv:HB4IHZz0t6YXbEMuMlmt5dC1hHo6T12I1BjjMVPkzTo=,tag:JBdRQwMLnUFkf2OBfZ+4GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n9l6uxhz0dt3v9qxmcp7492ftrnxlmtwq4yrzd4kr0j9zzkepa9ssqfq23
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaEc0RHBSVUhLMDEzY1Nl
            YUFINmp0K1dzbmtydjJOdnVQRjhrV0dRWENrCnNEZk8rRml0WXlYemlyUGZsUTM0
            elpzVWN1eXRPQjQ5dm9UbGEwQXpsZFkKLS0tIDBaSGd5N1h4R2FJQWdBWHdnREdX
            NGFsSFE1c0g5QTJHdnlxVkw5TXg2UTAKSbpzaBzCEPH8fz5UjfemJF1WwlmadCn4
            xX1MLKYljUNt8UJHSq0HmwFgNnPnB5EZ3ikoYt+Bw1aL95GX288PHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T08:42:00Z"
    mac: ENC[AES256_GCM,data:e43bi17C4XZIRL7mtkP3CQxB6M5AeD+c1cXFd068I01ik4jukjc5mu5984bZdjt5QmE+GOvDBSZnNRWnCKSxjJNHntNTAVNolDR0UpjRofnjQ8/4VjJTOyJgVVO79h7BnEWpon2iu7DwCWFFb7Q7lv5VQQg0BNZDVl6ENVXejFg=,iv:r2mq7aFnKWHSLt8w5FOMuoqUnv/oiTumwldXaZ+RZ1E=,tag:wZIMAS/SV04SJj3A9pVmWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
