apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:SZJwcvMoTc9l7KHvWMU+SfBC23N7quW1G2yUtt1mH5vXIv9x,iv:1Y2QIZsHz59DYVCHi7GTr/N1jEPj6VwQaaxUDKUFrus=,tag:1n6HPAl19nGei1BMHyyFNw==,type:str]
    credentials.json: ENC[AES256_GCM,data:IPT2IaJ/HZGfmwURl6Gl2nfvIujKaQ5Ssqt5yYbpfQE8hyRikl9C0p2IEq3qzg7Xu7ZSkJQK1+/ADB1vsUJVR7/6VACWgShqTpxx2/PjSKEZqzdobZhYWMsQHXFIcCnUcvNL/A81EYWpJmxPXe0CznlpNlY2ONBvvG6UEPiqeGC1DKfXiR/zGpjdwA6cuDJVgEDUJh4MwDBDN7QrSd30lklwb9FGe/Y11/eLfMVnTg==,iv:dpwZ5MTBVDfHBTo7oyEz1AZG5CpOgO49N1SbZJtct4M=,tag:Q5q6ddOZ5V5gmSO++H/6ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykegsmjhpgzqh7dw6d9tqgtyavqrr3w0mrrmgx33cyyc43uxd5gskezvvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQXBHL3VxaXhabVdJdHc4
            UjFpelIrQTZKek5NQXcvUUlORU80OXpaV21VCmhkRXptb1J2U3p6TW9ySzE0VEtl
            Y2FkSUxwRkI5eHR0KytGQ0xOaWloZVkKLS0tIGliQ2s5WU1RNzgxOUNrSlBLWXFE
            M0ZlN3ZucnEvQUplSlNBTVI0L2dwU0EKTOUmKJWUCl8bzAY6YwB8v6ztcqOmc9pi
            laQNb39XnLIFmRZEQydkQQzw0FOaPlG/gCGJwX43iKOG4VMNF4PN0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:48:30Z"
    mac: ENC[AES256_GCM,data:6EYpmmFOomBUWpeBwGFwjhteDlsVlj+aby4QH+0u1MTiWwB49mcV2jow9nJ5M0hYjEudl+6aU/mTlp2mNKaJprKSQuOblLwAQh5PxW2h+0r6qbwmozdbSg1QtprgQIf///yvtUoqhOZ9JKn7sKhupK7k/xMszdLM+CW5az2huvY=,iv:0LiYBXdaQWTkZU0YkgYXSU4okEmnXGD2w1DYxH9MCS4=,tag:qQrVFoxKVK6aguSxG5428A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
