apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ScoUGHo5NfRT4ZuUjRrj2GiJnxEOWptb,iv:k45VAQRn4NW73XQyRVZu6bzu90y2+ZtHT7MuL2Jwo0Y=,tag:HTpy38GzZy0kvADGOz9TXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n9l6uxhz0dt3v9qxmcp7492ftrnxlmtwq4yrzd4kr0j9zzkepa9ssqfq23
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVTRpdFhjWDhSaW5qREov
            Q1hrVjkxdTJXTnZ1Tk8yT2dRdm9LUGQ5VkYwClNGZXd1bjE1V3c2SDExb0dSSlFB
            SzY3Rk1iMURHaW1kTk9pR1gvVnhEdEEKLS0tIHpVQTNwUnMzbzNySjkyQkhGWDh5
            ZU9McjNVcDJQWHhneVpYa3pDUW5mL1EKoJDrt6HbqdMIXLgbqoQQWGa74QAm1N0S
            OYMuMZ1JxpEF5jrtnJ5vXk8tforcQNFKHWLqO29He4/5r6ut6tCSTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T19:03:38Z"
    mac: ENC[AES256_GCM,data:wRh5IIoNGG9OIRYjMCrvadAwEELIIp6AxevK8sniGjezdKPCKlN6y6atqlLjYmEzT4exB7b2ScS0ksKCB+b83WVCJZXJvH7NIg7qEcsxenMU2rn0U5h3Nh+2WAEHE+GPOAsjz6ZSwUvpzSALGAAKemMYEFSli84u2KSDy+JSyKw=,iv:AJsJ663wJafv0PqXtKHENYI/WwjUtDxapd/kWiPEChI=,tag:8558Bb4bbEBDPgmZFiWJ7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
