---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .AUTHENTIK_POSTGRESQL_USER }}"
        password: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
        ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        SECRET_ACCESS_KEY: "{{ .SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: authentik
        key: service-k3s-postgres
