---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: office
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        nextcloud-username: "{{ .NEXTCLOUD_USERNAME }}"
        nextcloud-password: "{{ .NEXTCLOUD_PASSWORD }}"
        smtp-username: "{{ .NEXTCLOUD_SMTP_USERNAME }}"
        smtp-password: "{{ .NEXTCLOUD_SMTP_PASS }}"
        smtp-host: mail.${SECRET_DOMAIN}
        # Postgresql
        database-username: &dbUser "{{ .NEXTCLOUD_DB_USER }}"
        database-password: &dbPass "{{ .NEXTCLOUD_DB_PASS }}"
        NEXTCLOUD_POSTGRES_HOST: nextcloud-postgresql
        NEXTCLOUD_DB_NAME: "{{ .NEXTCLOUD_DB_NAME }}"
        NEXTCLOUD_DB_USER: *dbUser
        NEXTCLOUD_DB_PASS: *dbPass
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Redis
        NEXTCLOUD_REDIS_PASSWORD: "{{ .NEXTCLOUD_REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: postgresql
