---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: office
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        nextcloud-username: "{{ .NEXTCLOUD_USERNAME }}"
        nextcloud-password: "{{ .NEXTCLOUD_PASSWORD }}"
        nextcloud-token: "{{ .NEXTCLOUD_TOKEN }}"
        smtp-username: "{{ .NEXTCLOUD_SMTP_USERNAME }}"
        smtp-password: "{{ .NEXTCLOUD_SMTP_PASSWORD }}"
        smtp-host: mail.${SECRET_DOMAIN}
        database-username: "{{ .NEXTCLOUD_DBUSER }}"
        database-password: "{{ .NEXTCLOUD_DBPASS }}"
        database-name: "{{ .NEXTCLOUD_DB_NAME }}"
  dataFrom:
    - extract:
        key: nextcloud
