---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-postgresql
  namespace: office
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: 13.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      existingSecret: nextcloud-secret
      secretKeys:
        userPasswordKey: NEXTCLOUD_DB_PASS
        adminPasswordKey: POSTGRES_SUPER_PASS
      username: ${NEXTCLOUD_DB_USER}
      database: ${NEXTCLOUD_DB_NAME}
    primary:
      persistence:
        enabled: true
        existingClaim: nextcloud-postgresql-pvc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
