---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-redis
  namespace: office
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 18.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        existingClaim: nextcloud-redis-pvc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      existingSecret: nextcloud-secret
      existingSecretPasswordKey: NEXTCLOUD_REDIS_PASSWORD
