---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis-pvc
  namespace: office
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
