---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: office
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: .config-pvc
  namespace: office
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 5Gi
