---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-postgresql-pvc
  namespace: security
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
