---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-authelia-database
    - name: cluster-apps-authelia-redis
  path: ./kubernetes/apps/security/authelia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia-database
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-longhorn-configs
  path: ./kubernetes/apps/security/authelia/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-longhorn-configs
  path: ./kubernetes/apps/security/authelia/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
